FROM node:20 AS build

WORKDIR /app

# Install deps
COPY package*.json ./
RUN npm install

# Copy source
COPY . .

# Build React app (Vite will use VITE_API_URL from .env)
RUN npm run build

FROM nginx:alpine

# Copy build output to Nginx web root
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80 for the web app
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
