version: "3.9"
services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TechInTheBoxDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  frontend:
    build: ./client
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./server
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - db
volumes:
  db_data:
